"""validated and serialized

Revision ID: 3dd21e4d2761
Revises: ff358bc9332d
Create Date: 2025-01-24 17:04:12.102678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd21e4d2761'
down_revision = 'ff358bc9332d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
